# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/node:10-browsers
      - image: circleci/node:10-jessie-browsers
      - image: circleci/node:10-stretch-browsers
      - image: circleci/node:10.6-browsers
      - image: circleci/node:10.6-jessie-browsers
      - image: circleci/node:10.6-stretch-browsers
      - image: circleci/node:10.6.0-browsers
      - image: circleci/node:10.6.0-jessie-browsers
      - image: circleci/node:10.6.0-stretch-browsers
      - image: circleci/node:6-browsers
      - image: circleci/node:6-jessie-browsers
      - image: circleci/node:6-stretch-browsers
      - image: circleci/node:6.14-browsers
      - image: circleci/node:6.14-jessie-browsers
      - image: circleci/node:6.14-stretch-browsers
      - image: circleci/node:6.14.3-browsers
      - image: circleci/node:6.14.3-jessie-browsers
      - image: circleci/node:6.14.3-stretch-browsers
      - image: circleci/node:8-browsers
      - image: circleci/node:8-jessie-browsers
      - image: circleci/node:8-stretch-browsers

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test
