# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/mysql:5
      - image: circleci/mysql:5.5
      - image: circleci/mysql:5.6-ram
      - image: circleci/mysql:5.7
      - image: circleci/mysql:8
      - image: circleci/mysql:8-ram
      - image: circleci/mysql:8.0
      - image: circleci/mysql:8.0-ram
      - image: circleci/mysql:8.0.11
      - image: circleci/mysql:8.0.11-ram
      - image: circleci/mysql:8.0.2
      - image: circleci/mysql:8.0.2-ram
      - image: circleci/mysql:8.0.3
      - image: circleci/mysql:8.0.3-ram
      - image: circleci/mysql:8.0.4
      - image: circleci/mysql:8.0.4-ram
      - image: circleci/mysql:8.0.4-rc
      - image: circleci/mysql:8.0.4-rc-ram
      - image: circleci/mysql:latest
      - image: circleci/mysql:latest-ram


    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test
